#!/ibin/bash
# Step 1: Login Authentication

echo "LOGIN SYSTEM"

read -p "Enter Username: " username
read -sp "Enter Password: " password
echo

# Check username and password
if [ "$username" != "admin" ] || [ "$password" != "1234" ]; then
    echo "Login Failed"
    exit
fi

echo "Login Successful"
echo

# Step 2: Menu Driven Calculator

while true
do
    echo "     MENU DRIVEN CALCULATOR"
    echo "1. Addition"
    echo "2. Subtraction"
    echo "3. Multiplication"
    echo "4. Division"
    echo "5. Print Multiplication Table"
    echo "6. Exit"

    read -p "Enter your choice: " choice

    case $choice in

        1)
            read -p "Enter first number: " a
            read -p "Enter second number: " b
            result=$((a + b))
            echo "Addition = $result"
            ;;

        2)
            read -p "Enter first number: " a
            read -p "Enter second number: " b
            result=$((a - b))
            echo "Subtraction = $result"
            ;;

        3)
            read -p "Enter first number: " a
            read -p "Enter second number: " b
            result=$((a * b))
            echo "Multiplication = $result"
            ;;

        4)
            read -p "Enter first number: " a
            read -p "Enter second number: " b

            if [ "$b" -eq 0 ]; then
                echo "Division by zero is not allowed!"
            else
                result=$((a / b))
                echo "Division = $result"
            fi
            ;;

        5)
            read -p "Enter a number: " n

            echo "Multiplication Table of $n"

            for ((i=1; i<=10; i++))
            do
                echo "$n x $i = $((n * i))"
            done
