#!/bin/bash
echo "Enter Student Name:"
read name

echo "Enter Roll Number:"
read roll

echo "Enter Number of Subjects:"
read n

total=0
fail=0

for ((i=1; i<=n; i++))
do
        echo "Enter Marks for Subject $i:"
        read mark

        total=$((total + mark))

        if [ $mark -lt 40 ]
        then
                fail=1
        fi
done

average=$((total / n))

if [ $fail -eq 1 ]
then
        grade="F"
        result="Fail"

else
        if [ $average -ge 80 ]
        then
                grade="A+"

        elif [ $average -ge 70 ]
        then
                grade="A"

        elif [ $average -ge 60 ]
        then
                grade="A-"

        elif [ $average -ge 50 ]
        then
                grade="B"

        elif [ $average -ge 40 ]
        then
                grade="C"

        else
                grade="F"
        fi

        if [ "$grade" = "F" ]
        then
                result="Fail"
        else
                result="Pass"
        fi
fi

echo
echo "Student Result"
echo "Student Name : $name"
echo "Roll Number  : $roll"
echo "Total Marks  : $total"
echo "Average Marks: $average"
echo "Grade        : $grade"
echo "Result       : $result"