#!/bin/bash

correct_username="Kamrulbx"
correct_password="10920770"

echo "===== Login Authentication ====="

read -p "Enter Username: " username
read -sp "Enter Password: " password
echo

if [ "$username" = "$correct_username" ] && [ "$password" = "$correct_password" ]
then
    echo "Login Successful!"
    echo "Opening Calculator..."

    read -p "Enter First Number: " num1
    read -p "Enter Second Number: " num2

    echo "Choose Operation:"
    echo "1. Addition"
    echo "2. Subtraction"
    echo "3. Multiplication"
    echo "4. Division"

    read -p "Enter your choice (1-4): " choice

    if [ "$choice" -eq 1 ]
    then
        result=$((num1 + num2))
        echo "Result = $result"

    elif [ "$choice" -eq 2 ]
    then
        result=$((num1 - num2))
        echo "Result = $result"

    elif [ "$choice" -eq 3 ]
    then
        result=$((num1 * num2))
        echo "Result = $result"

    elif [ "$choice" -eq 4 ]
    then
        if [ "$num2" -eq 0 ]
        then
            echo "Division by zero is not allowed!"
        else
            result=$((num1 / num2))
            echo "Result = $result"
        fi

    else
        echo "Invalid Choice!"
    fi

else
    echo "Login Failed!"
    exit
fi